name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Chekout code
      uses: actions/checkout@v4
    - name: Set up bun
      uses: oven-sh/setup-bun@v2
      
    - name: Install dependencies
      run: bun install
    - name: Build app
      run: bun run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build
